package com.lds.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DocumentStatusAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentStatusAllPropertiesEquals(DocumentStatus expected, DocumentStatus actual) {
        assertDocumentStatusAutoGeneratedPropertiesEquals(expected, actual);
        assertDocumentStatusAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentStatusAllUpdatablePropertiesEquals(DocumentStatus expected, DocumentStatus actual) {
        assertDocumentStatusUpdatableFieldsEquals(expected, actual);
        assertDocumentStatusUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentStatusAutoGeneratedPropertiesEquals(DocumentStatus expected, DocumentStatus actual) {
        assertThat(actual)
            .as("Verify DocumentStatus auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentStatusUpdatableFieldsEquals(DocumentStatus expected, DocumentStatus actual) {
        assertThat(actual)
            .as("Verify DocumentStatus relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getColor()).as("check color").isEqualTo(expected.getColor()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentStatusUpdatableRelationshipsEquals(DocumentStatus expected, DocumentStatus actual) {
        // empty method
    }
}
