package com.lds.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DocumentReferenceAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentReferenceAllPropertiesEquals(DocumentReference expected, DocumentReference actual) {
        assertDocumentReferenceAutoGeneratedPropertiesEquals(expected, actual);
        assertDocumentReferenceAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentReferenceAllUpdatablePropertiesEquals(DocumentReference expected, DocumentReference actual) {
        assertDocumentReferenceUpdatableFieldsEquals(expected, actual);
        assertDocumentReferenceUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentReferenceAutoGeneratedPropertiesEquals(DocumentReference expected, DocumentReference actual) {
        assertThat(actual)
            .as("Verify DocumentReference auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentReferenceUpdatableFieldsEquals(DocumentReference expected, DocumentReference actual) {
        assertThat(actual)
            .as("Verify DocumentReference relevant properties")
            .satisfies(a -> assertThat(a.getDate()).as("check date").isEqualTo(expected.getDate()))
            .satisfies(a -> assertThat(a.getReferenceNo()).as("check referenceNo").isEqualTo(expected.getReferenceNo()))
            .satisfies(a -> assertThat(a.getDocumentTitle()).as("check documentTitle").isEqualTo(expected.getDocumentTitle()))
            .satisfies(a -> assertThat(a.getAuthor()).as("check author").isEqualTo(expected.getAuthor()))
            .satisfies(a -> assertThat(a.getDateReleased()).as("check dateReleased").isEqualTo(expected.getDateReleased()))
            .satisfies(a ->
                assertThat(a.getSubmittedToSirKing()).as("check submittedToSirKing").isEqualTo(expected.getSubmittedToSirKing())
            )
            .satisfies(a -> assertThat(a.getRemarks()).as("check remarks").isEqualTo(expected.getRemarks()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentReferenceUpdatableRelationshipsEquals(DocumentReference expected, DocumentReference actual) {
        assertThat(actual)
            .as("Verify DocumentReference relationships")
            .satisfies(a -> assertThat(a.getTypeOfDocument()).as("check typeOfDocument").isEqualTo(expected.getTypeOfDocument()));
    }
}
