package com.lds.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DocumentHistoryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentHistoryAllPropertiesEquals(DocumentHistory expected, DocumentHistory actual) {
        assertDocumentHistoryAutoGeneratedPropertiesEquals(expected, actual);
        assertDocumentHistoryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentHistoryAllUpdatablePropertiesEquals(DocumentHistory expected, DocumentHistory actual) {
        assertDocumentHistoryUpdatableFieldsEquals(expected, actual);
        assertDocumentHistoryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentHistoryAutoGeneratedPropertiesEquals(DocumentHistory expected, DocumentHistory actual) {
        assertThat(actual)
            .as("Verify DocumentHistory auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentHistoryUpdatableFieldsEquals(DocumentHistory expected, DocumentHistory actual) {
        assertThat(actual)
            .as("Verify DocumentHistory relevant properties")
            .satisfies(a -> assertThat(a.getDocumentId()).as("check documentId").isEqualTo(expected.getDocumentId()))
            .satisfies(a -> assertThat(a.getDocumentType()).as("check documentType").isEqualTo(expected.getDocumentType()))
            .satisfies(a -> assertThat(a.getAction()).as("check action").isEqualTo(expected.getAction()))
            .satisfies(a -> assertThat(a.getChangedBy()).as("check changedBy").isEqualTo(expected.getChangedBy()))
            .satisfies(a -> assertThat(a.getTimestamp()).as("check timestamp").isEqualTo(expected.getTimestamp()))
            .satisfies(a -> assertThat(a.getPreviousValue()).as("check previousValue").isEqualTo(expected.getPreviousValue()))
            .satisfies(a -> assertThat(a.getNewValue()).as("check newValue").isEqualTo(expected.getNewValue()))
            .satisfies(a -> assertThat(a.getRemarks()).as("check remarks").isEqualTo(expected.getRemarks()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentHistoryUpdatableRelationshipsEquals(DocumentHistory expected, DocumentHistory actual) {
        // empty method
    }
}
