package com.lds.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class OfficeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOfficeAllPropertiesEquals(Office expected, Office actual) {
        assertOfficeAutoGeneratedPropertiesEquals(expected, actual);
        assertOfficeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOfficeAllUpdatablePropertiesEquals(Office expected, Office actual) {
        assertOfficeUpdatableFieldsEquals(expected, actual);
        assertOfficeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOfficeAutoGeneratedPropertiesEquals(Office expected, Office actual) {
        assertThat(actual)
            .as("Verify Office auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOfficeUpdatableFieldsEquals(Office expected, Office actual) {
        assertThat(actual)
            .as("Verify Office relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getShortName()).as("check shortName").isEqualTo(expected.getShortName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOfficeUpdatableRelationshipsEquals(Office expected, Office actual) {
        // empty method
    }
}
