package com.lds.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ReceivedDocumentAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReceivedDocumentAllPropertiesEquals(ReceivedDocument expected, ReceivedDocument actual) {
        assertReceivedDocumentAutoGeneratedPropertiesEquals(expected, actual);
        assertReceivedDocumentAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReceivedDocumentAllUpdatablePropertiesEquals(ReceivedDocument expected, ReceivedDocument actual) {
        assertReceivedDocumentUpdatableFieldsEquals(expected, actual);
        assertReceivedDocumentUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReceivedDocumentAutoGeneratedPropertiesEquals(ReceivedDocument expected, ReceivedDocument actual) {
        assertThat(actual)
            .as("Verify ReceivedDocument auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReceivedDocumentUpdatableFieldsEquals(ReceivedDocument expected, ReceivedDocument actual) {
        assertThat(actual)
            .as("Verify ReceivedDocument relevant properties")
            .satisfies(a -> assertThat(a.getDate()).as("check date").isEqualTo(expected.getDate()))
            .satisfies(a -> assertThat(a.getDocumentTitle()).as("check documentTitle").isEqualTo(expected.getDocumentTitle()))
            .satisfies(a -> assertThat(a.getTransactionType()).as("check transactionType").isEqualTo(expected.getTransactionType()))
            .satisfies(a -> assertThat(a.getDays()).as("check days").isEqualTo(expected.getDays()))
            .satisfies(a -> assertThat(a.getDueDate()).as("check dueDate").isEqualTo(expected.getDueDate()))
            .satisfies(a -> assertThat(a.getDaysBeforeDue()).as("check daysBeforeDue").isEqualTo(expected.getDaysBeforeDue()))
            .satisfies(a -> assertThat(a.getDateReleased()).as("check dateReleased").isEqualTo(expected.getDateReleased()))
            .satisfies(a -> assertThat(a.getRemarks()).as("check remarks").isEqualTo(expected.getRemarks()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReceivedDocumentUpdatableRelationshipsEquals(ReceivedDocument expected, ReceivedDocument actual) {
        assertThat(actual)
            .as("Verify ReceivedDocument relationships")
            .satisfies(a -> assertThat(a.getRequestedAction()).as("check requestedAction").isEqualTo(expected.getRequestedAction()))
            .satisfies(a -> assertThat(a.getTypeOfDocument()).as("check typeOfDocument").isEqualTo(expected.getTypeOfDocument()))
            .satisfies(a -> assertThat(a.getOffice()).as("check office").isEqualTo(expected.getOffice()))
            .satisfies(a -> assertThat(a.getResponsiblePerson()).as("check responsiblePerson").isEqualTo(expected.getResponsiblePerson()))
            .satisfies(a -> assertThat(a.getDocumentStatus()).as("check documentStatus").isEqualTo(expected.getDocumentStatus()));
    }
}
