package com.lds.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class RequestedActionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRequestedActionAllPropertiesEquals(RequestedAction expected, RequestedAction actual) {
        assertRequestedActionAutoGeneratedPropertiesEquals(expected, actual);
        assertRequestedActionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRequestedActionAllUpdatablePropertiesEquals(RequestedAction expected, RequestedAction actual) {
        assertRequestedActionUpdatableFieldsEquals(expected, actual);
        assertRequestedActionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRequestedActionAutoGeneratedPropertiesEquals(RequestedAction expected, RequestedAction actual) {
        assertThat(actual)
            .as("Verify RequestedAction auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRequestedActionUpdatableFieldsEquals(RequestedAction expected, RequestedAction actual) {
        assertThat(actual)
            .as("Verify RequestedAction relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRequestedActionUpdatableRelationshipsEquals(RequestedAction expected, RequestedAction actual) {
        // empty method
    }
}
