package com.lds.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ResponsiblePersonAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertResponsiblePersonAllPropertiesEquals(ResponsiblePerson expected, ResponsiblePerson actual) {
        assertResponsiblePersonAutoGeneratedPropertiesEquals(expected, actual);
        assertResponsiblePersonAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertResponsiblePersonAllUpdatablePropertiesEquals(ResponsiblePerson expected, ResponsiblePerson actual) {
        assertResponsiblePersonUpdatableFieldsEquals(expected, actual);
        assertResponsiblePersonUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertResponsiblePersonAutoGeneratedPropertiesEquals(ResponsiblePerson expected, ResponsiblePerson actual) {
        assertThat(actual)
            .as("Verify ResponsiblePerson auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertResponsiblePersonUpdatableFieldsEquals(ResponsiblePerson expected, ResponsiblePerson actual) {
        assertThat(actual)
            .as("Verify ResponsiblePerson relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getPosition()).as("check position").isEqualTo(expected.getPosition()))
            .satisfies(a -> assertThat(a.getEmail()).as("check email").isEqualTo(expected.getEmail()))
            .satisfies(a -> assertThat(a.getContactNo()).as("check contactNo").isEqualTo(expected.getContactNo()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertResponsiblePersonUpdatableRelationshipsEquals(ResponsiblePerson expected, ResponsiblePerson actual) {
        // empty method
    }
}
