package com.lds.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TransactionTypeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransactionTypeAllPropertiesEquals(TransactionType expected, TransactionType actual) {
        assertTransactionTypeAutoGeneratedPropertiesEquals(expected, actual);
        assertTransactionTypeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransactionTypeAllUpdatablePropertiesEquals(TransactionType expected, TransactionType actual) {
        assertTransactionTypeUpdatableFieldsEquals(expected, actual);
        assertTransactionTypeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransactionTypeAutoGeneratedPropertiesEquals(TransactionType expected, TransactionType actual) {
        assertThat(actual)
            .as("Verify TransactionType auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransactionTypeUpdatableFieldsEquals(TransactionType expected, TransactionType actual) {
        assertThat(actual)
            .as("Verify TransactionType relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getTargetDays()).as("check targetDays").isEqualTo(expected.getTargetDays()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransactionTypeUpdatableRelationshipsEquals(TransactionType expected, TransactionType actual) {
        // empty method
    }
}
