package com.lds.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TypeOfDocumentAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTypeOfDocumentAllPropertiesEquals(TypeOfDocument expected, TypeOfDocument actual) {
        assertTypeOfDocumentAutoGeneratedPropertiesEquals(expected, actual);
        assertTypeOfDocumentAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTypeOfDocumentAllUpdatablePropertiesEquals(TypeOfDocument expected, TypeOfDocument actual) {
        assertTypeOfDocumentUpdatableFieldsEquals(expected, actual);
        assertTypeOfDocumentUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTypeOfDocumentAutoGeneratedPropertiesEquals(TypeOfDocument expected, TypeOfDocument actual) {
        assertThat(actual)
            .as("Verify TypeOfDocument auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTypeOfDocumentUpdatableFieldsEquals(TypeOfDocument expected, TypeOfDocument actual) {
        assertThat(actual)
            .as("Verify TypeOfDocument relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTypeOfDocumentUpdatableRelationshipsEquals(TypeOfDocument expected, TypeOfDocument actual) {
        // empty method
    }
}
