# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: NzZlMWY3YzI5ZmE5ZjlhYTA3MTE5NGU4MWI1NzI3NDM1ZGI0Y2U1ODlkMGI5ZjQ2NTVjNzQzMzU3ZDJhNDJjNDVlODk5OGViZjc3MDdlN2M4YzhlOTU3NGQzNmIzOTcyOWFmNGM1OTM0OGQ1ZWQ2NGRhMjQ0NjNiMzIyMzA4NGM=
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    username: legal
    password:
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    username: root
    password:
